name: Build

on: 
    push:
        branch: ["main"]
    pull_request:
        branch: ["main"]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-latest }
        - { name: Windows, os: windows-latest }
        - { name: MacOS,   os: macos-latest }
    steps:
    - name: Get sources
      uses: actions/checkout@v4
    - name: Set up ninja
      uses: ./.github/actions/setup-ninja
    - name: Set up SDL
      id: sdl
      uses: libsdl-org/setup-sdl@v1
      with:
        version: sdl3-latest
    - name: Get sources
      uses: actions/checkout@v3
      cmake-generator: Ninja
    - name: Configure CMake
      run: cmake -B build ${{ matrix.platform.flags }}
      run: cmake -B build -GNinja ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/